warps: []
spawn:
  min:
    ==: org.bukkit.Location
    world: world
    x: -175.0
    y: 0.0
    z: -175.0
    pitch: 0.0
    yaw: 0.0
  max:
    ==: org.bukkit.Location
    world: world
    x: 175.0
    y: 255.0
    z: 175.0
    pitch: 0.0
    yaw: 0.0
  point:
    ==: org.bukkit.Location
    world: world
    x: 0.0
    y: 85.0
    z: 0.0
    pitch: 0.0
    yaw: 0.0
redis:
  ip: 127.0.0.1
  port: 6379
  password: password