name: Gondola
main: au.net.snowblind.gondola.Gondola
version: 0.2
api-version: 1.16
author: insyder1201
depend: [Vault]
commands:
  help:
    description: List commands available
    usage: /help [section]
  tp:
    description: Request to teleport to player
    usage: /tp <player>
  tpaccept:
    description: Accept the latest teleport request
    usage: /tpaccept
  msg:
    description: Privately message a player
    usage: /msg <player> <message>
  r:
    description: Privately reply to a player
    usage: /r <message>
  home:
    description: Teleport to one of your homes
    usage: /home [home]
  sethome:
    description: Set one of your homes
    usage: /sethome [home]
  listhomes:
    description: List your homes
    usage: /listhomes
    aliases: [homes]
  delhome:
    description: Delete a home
    usage: /delhome <home>
  warp:
    description: Teleport to a warp or list warps
    usage: /warp [warp]
  setwarp:
    description: Set a warp
    usage: /setwarp [warp]
  delwarp:
    description: Delete a warp
    usage: /delwarp <warp>
  setclanbanner:
    description: Set your clan's banner
    usage: /setclanbanner
  createclan:
    description: Create a new clan
    usage: /createclan <name>
  deleteclan:
    description: Deletes the clan you own
    usage: /deleteclan
  setclancolour:
    description: Set the clan colour of your clan
    usage: /setclancolour <colour>
  listclans:
    description: List the currently existing clans
    usage: /listclans
  claninvite:
    description: Invite player to your clan
    usage: /claninvite <player>
  acceptinvite:
    description: Accept invite to clan
    usage: /acceptinvite
  clankick:
    description: Kick player from your clan
    usage: /clankick <player>
  claninfo:
    description: Get information on a clan
    usage: /claninfo [clan]