name: Gondola
main: au.net.snowblind.gondola.Gondola
version: 0.2
api-version: 1.16
author: insyder1201
depend: [Vault]
commands:
  help:
    description: List commands available
    usage: /help [section]
  spawn:
    description: Teleport to spawn
    usage: /spawn
  setspawn:
    description: Set spawn point
    usage: /setspawn
    permission: gondola.setspawn
  nick:
    description: Set your nickname
    usage: /nickname
    permission: gondola.nickname
  tp:
    description: Request to teleport to player
    usage: /tp <player>
    aliases: [tpa]
  tpaccept:
    description: Accept the latest teleport request
    usage: /tpaccept
  msg:
    description: Privately message a player
    usage: /msg <player> <message>
  r:
    description: Privately reply to a player
    usage: /r <message>
  home:
    description: Teleport to one of your homes
    usage: /home [home]
  sethome:
    description: Set one of your homes
    usage: /sethome [home]
  delhome:
    description: Delete a home
    usage: /delhome <home>
  warp:
    description: Teleport to a warp or list warps
    usage: /warp [warp]
  setwarp:
    description: Set a warp
    usage: /setwarp [warp]
    permission: gondola.setwarp
  delwarp:
    description: Delete a warp
    usage: /delwarp <warp>
    permission: gondola.delwarp
  updatespawn:
    description: Replaces spawn's banners with your clan's banners
    usage: /updatespawn
    permission: gondola.updatespawn
  createclan:
    description: Create a new clan
    usage: /createclan <name>
    aliases: [ccreate]
  clan:
    description: Clan admin commands
    usage: /clan <command>
    aliases: [c]
  clanhome:
    description: Teleport to your clan's home
    usage: /clanhome
    aliases: [chome]
  listclans:
    description: List the currently existing clans
    usage: /listclans
    aliases: [clist]
  acceptinvite:
    description: Accept invite to clan
    usage: /acceptinvite
    aliases: [accept]
  claninfo:
    description: Get information on a clan
    usage: /claninfo [clan]
    aliases: [cinfo]